AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation managed taskdefinition
Parameters:
  RepositoryURL:
    Type: String
    Description: URL to repository, where the container is, e.g. 012345678910.dkr.ecr.eu-west-1.amazonaws.com
  CacheHost:
    Type: String
    Description: URL to cache , e.g. name.4xakoi.cfg.euw1.cache.amazonaws.com 
  CachePort:
    Type: Number
    Default: 11211
    Description: port number
  ECSTaskRoleName:
    Type: String
    Default: dev-digiroad2-ecs-task-role
    Description: Name of ECS task definition task role
  ApiS3BucketName:
    Type: String
    Default: dev-vayla-digiroad2-api-store-bucket
    Description: Name of s3 bucket for apis
  ApiS3ObjectTTLSeconds:
    Type: Number
    Default: 300
    Description: Seconds, how long s3 object can be fetched after last modification

Resources:
  ECSTaskExecutionRoleForTaskDefinitionDigiroad:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: ecsTaskExecutionRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  # Allow the ECS Tasks to download images from ECR
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'

                  # Allow the ECS tasks to upload logs to CloudWatch
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:CreateLogGroup'

                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:GetParametersByPath'
                Resource: '*'

  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /dev/Digiroad-logs
      RetentionInDays: 180

  Taskdefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - ECSTaskExecutionRoleForTaskDefinitionDigiroad
      - ECSLogGroup
    Properties:
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRoleForTaskDefinitionDigiroad.Arn
      TaskRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ECSTaskRoleName}'
      Memory: '2048'
      Family: digiroad2-dev
      Cpu: '1024'
      ContainerDefinitions:
        -
          Cpu: 0
          memory: 2048
          Image: !Sub '${RepositoryURL}:latest'
          Name: digiroad2
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /dev/Digiroad-logs
              awslogs-region: eu-west-1
              awslogs-stream-prefix: ecs
              awslogs-create-group: true
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
          Environment:
            - Name: containerCPU
              Value: -XX:ActiveProcessorCount=1
            - Name: REGION
              Value: eu-west-1
            - Name: speedLimitProvider
              Value: fi.liikennevirasto.digiroad2.service.linearasset.SpeedLimitService
            - Name: userProvider
              Value: fi.liikennevirasto.digiroad2.dao.PostGISUserProvider
            - Name: municipalityProvider
              Value: fi.liikennevirasto.digiroad2.dao.PostGISMunicipalityProvider
            - Name: eventBus
              Value: 'fi.liikennevirasto.digiroad2.DigiroadEventBus'
            - Name: kgv.endpoint
              Value: 'https://api.vaylapilvi.fi/paikkatiedot/ogc/features/v1/collections/'
            - Name: authenticationTestMode
              Value: 'false'
            - Name: vkmUrl
              Value: 'https://api.vaylapilvi.fi'
            - Name: vallu.server.sending_enabled
              Value: 'false'
            - Name: vallu.server.address
              Value: 'https://api.testivaylapilvi.fi/koontikartta/pysakit/xml/'
            - Name: http.proxySet
              Value: 'true'
            - Name: http.proxyHost
              Value: '127.0.0.1'
            - Name: http.proxyPort
              Value: '3128'
            - Name: http.nonProxyHosts
              Value: '172.17.*|localhost|127.*'
            - Name: feedbackAssetsEndPoint
              Value: 'https://digiroaddev.testivaylapilvi.fi/'
            - Name: bonecp.jdbcUrl
              Value: 'jdbc:postgresql://ddw6gldo8fiqt4.c8sq5c8rj3gu.eu-west-1.rds.amazonaws.com:5432/digiroad2'
            - Name: bonecp.username
              Value: 'digiroad2dbuser'
            - Name: emailTo
              Value: 'info@digiroad.fi'
            - Name: emailHost
              Value: 'email-smtp.eu-west-1.amazonaws.com'
            - Name: emailPort
              Value: '587'
            - Name: emailFrom
              Value: 'noreply.digiroad@vaylapilvi.fi'
            - Name: env
              Value: 'dev'
            - Name: caching
              Value: 'true'
            - Name: cacheHostname
              Value: !Sub '${CacheHost}'
            - Name: cacheHostPort
              Value: !Sub '${CachePort}' 
            - Name: cacheTTL
              Value: '72000'
            - Name: rasterServiceUrl
              Value: 'https://api.vaylapilvi.fi/rasteripalvelu-mml'
            - Name: apiS3BucketName
              Value: !Sub '${ApiS3BucketName}'
            - Name: apiS3ObjectTTLSeconds
              Value: !Sub '${ApiS3ObjectTTLSeconds}'
          Secrets:
            - Name: bonecp.password
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/bonecp.password'
            - Name: vkm.apikey
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/apikey/viitekehysmuunnin'
            - Name: rasterService.apikey
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/apikey/mml_map'
            - Name: ses.username
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/ses_username'
            - Name: ses.password
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/ses_password'
            - Name: vvhRest.password
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/vvhRest.password'
            - Name: kgv.apikey
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/apikey/kgv.apikey'
            - Name: vallu.apikey
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/qa/apikey/vallu.apikey'
            - Name: googlemapapi.client_id
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/googlemapapi.client_id'
            - Name: googlemapapi.crypto_key
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/googlemapapi.crypto_key'
          HealthCheck:
            StartPeriod: 15
            Command:
              - CMD-SHELL
              - curl -f http://127.0.0.1:8080/api/ping/ || exit 1
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Tags:
        - Key: Name
          Value: digiroad2
        - Key: Environment
          Value: dev
        - Key: Owner
          Value: vayla
        - Key: Project
          Value: digiroad2
