AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation managed taskdefinition
Parameters:
  RepositoryURL:
    Type: String
    Description: URL to repository, where the container is, e.g. 012345678910.dkr.ecr.eu-west-1.amazonaws.com
  CacheHost:
    Type: String
    Description: URL to cache , e.g. name.4xakoi.cfg.euw1.cache.amazonaws.com
  CachePort:
    Type: Number
    Default: 11211
    Description: port number
  ECSTaskRoleName:
    Type: String
    Default: qa-digiroad2-ecs-task-role
    Description: Name of ECS task definition task role
  ApiS3BucketName:
    Type: String
    Default: qa-vayla-digiroad2-api-store-bucket
    Description: Name of s3 bucket for apis

Resources:
  ECSTaskExecutionRoleForTaskDefinitionDigiroad:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: ecsTaskExecutionRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  # Allow the ECS Tasks to download images from ECR
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'

                  # Allow the ECS tasks to upload logs to CloudWatch
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:CreateLogGroup'

                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:GetParametersByPath'
                Resource: '*'

  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /qa/Digiroad-logs
      RetentionInDays: 180


  Taskdefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - ECSTaskExecutionRoleForTaskDefinitionDigiroad
      - ECSLogGroup
    Properties:
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRoleForTaskDefinitionDigiroad.Arn
      TaskRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ECSTaskRoleName}'
      Memory: '4096'
      Family: digiroad2-qa
      Cpu: '2048'
      ContainerDefinitions:
        -
          Cpu: 0
          memory: 4096
          Image: !Sub '${RepositoryURL}:qa'
          Name: digiroad2
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /qa/Digiroad-logs
              awslogs-region: eu-west-1
              awslogs-stream-prefix: ecs
              awslogs-create-group: true
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
          Environment:
            - Name: containerCPU
              Value: -XX:ActiveProcessorCount=2
            - Name: REGION
              Value: eu-west-1
            - Name: speedLimitProvider
              Value: fi.liikennevirasto.digiroad2.service.linearasset.SpeedLimitService
            - Name: userProvider
              Value: fi.liikennevirasto.digiroad2.dao.PostGISUserProvider
            - Name: municipalityProvider
              Value: fi.liikennevirasto.digiroad2.dao.PostGISMunicipalityProvider
            - Name: eventBus
              Value: 'fi.liikennevirasto.digiroad2.DigiroadEventBus'
            - Name: useVVHGeometry
              Value: 'true'
            - Name: vvhServiceHost
              Value: 'haproxy.vayla.fi'
            - Name: vvhRestApiEndPoint
              Value: 'https://haproxy.vayla.fi:2027/vvhdata/'
            - Name: vvhRoadlink.frozen
              Value: 'false'
            - Name: viiteRestApiEndPoint
              Value: 'https://api.testivaylapilvi.fi/viite/api/viite/'
            - Name: authenticationTestMode
              Value: 'false'
            - Name: vkmUrl
              Value: 'https://api.vaylapilvi.fi'
            - Name: vallu.server.sending_enabled
              Value: 'false'
            - Name: vallu.server.address
              Value: ''
            - Name: viite.importTimeStamp
              Value: '1510876800000'
            - Name: http.proxySet
              Value: 'true'
            - Name: http.proxyHost
              Value: '127.0.0.1'
            - Name: http.proxyPort
              Value: '3128'
            - Name: http.nonProxyHosts
              Value: '172.17.*|localhost|127.*'
            - Name: feedbackAssetsEndPoint
              Value: 'https://digiroadtest.testivaylapilvi.fi/'
            - Name: bonecp.jdbcUrl
              Value: 'jdbc:postgresql://rdspg13test.chw6qe2cqnfv.eu-west-1.rds.amazonaws.com:5432/digiroadtest'
            - Name: bonecp.username
              Value: 'digiroadtest'
            - Name: oag.username
              Value: 'svc_clouddr'
            - Name: emailTo
              Value: 'info@digiroad.fi'
            - Name: emailHost
              Value: 'email-smtp.eu-west-1.amazonaws.com'
            - Name: emailPort
              Value: '587'
            - Name: emailFrom
              Value: 'noreply.digiroad@vaylapilvi.fi'
            - Name: env
              Value: 'qa'
            - Name: caching
              Value: 'true'
            - Name: cacheHostname
              Value: !Sub '${CacheHost}'
            - Name: cacheHostPort
              Value: !Sub '${CachePort}'
            - Name: cacheTTL
              Value: '72000'
            - Name: rasterServiceUrl
              Value: 'https://api.vaylapilvi.fi/rasteripalvelu-mml'
            - Name: apiS3BucketName
              Value: !Sub '${ApiS3BucketName}'
          Secrets:
            - Name: bonecp.password
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/qa/bonecp.password'
            - Name: viite.apikey
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/qa/apikey/viite'
            - Name: vkm.apikey
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/qa/apikey/viitekehysmuunnin'
            - Name: rasterService.apikey
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/apikey/mml_map'
            - Name: ses.username
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/qa/ses_username'
            - Name: ses.password
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/qa/ses_password'
            - Name: oag.password
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/qa/authentication.oag.basic.password'
            - Name: googlemapapi.client_id
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/qa/googlemapapi.client_id'
            - Name: googlemapapi.crypto_key
              ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/qa/googlemapapi.crypto_key'
          HealthCheck:
            StartPeriod: 15
            Command:
              - CMD-SHELL
              - curl -f http://127.0.0.1:8080/api/ping/ || exit 1
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Tags:
        - Key: Name
          Value: digiroad2
        - Key: Environment
          Value: qa
        - Key: Owner
          Value: vayla
        - Key: Project
          Value: digiroad2
