package fi.liikennevirasto.digiroad2.util

import org.scalatest.{FunSuite, Matchers}
import slick.driver.JdbcDriver.backend.Database
import Database.dynamicSession
import fi.liikennevirasto.digiroad2.asset.AutoGeneratedUsername
import slick.jdbc.StaticQuery.interpolation

class ReplaceAutoGeneratedUsernamesSpec extends FunSuite with Matchers {

  def runWithRollback(test: => Unit): Unit = {
    TestTransactions.runWithRollback()(test)
  }

  test("Update 'vvh_generated' and 'vvh_modified'") {
    runWithRollback {
      val ids = List.tabulate(1000)(_ +1000000000)
      ids.foreach { id =>
        sqlu"insert into ASSET (ID,ASSET_TYPE_ID,CREATED_BY,MUNICIPALITY_CODE, MODIFIED_BY) values ($id,220,'vvh_generated',235, 'vvh_modified')".execute
      }
      ReplaceAutoGeneratedUsernames.main(true)
      val idsAsString = ids.mkString("(", ",", ")")
      val updatedValues = sql"select CREATED_BY, MODIFIED_BY from asset where id in #$idsAsString".as[(String, String)].list

      updatedValues.foreach { values =>
        values._1 should be(AutoGeneratedUsername.generatedInUpdate)
        values._2 should be(AutoGeneratedUsername.automaticAdjustment)
      }
    }
  }

  test("Update 'vvh_mtkclass_default' and 'auto_generation'") {
    runWithRollback {
      val ids = List.tabulate(1000)(_ +1000000000)
      ids.foreach { id =>
        sqlu"insert into ASSET (ID,ASSET_TYPE_ID,CREATED_BY,MUNICIPALITY_CODE, MODIFIED_BY) values ($id,220,'vvh_mtkclass_default',235, 'auto_generation')".execute
      }
      ReplaceAutoGeneratedUsernames.main(true)
      val idsAsString = ids.mkString("(", ",", ")")
      val updatedValues = sql"select CREATED_BY, MODIFIED_BY from asset where id in #$idsAsString".as[(String, String)].list

      updatedValues.foreach { values =>
        values._1 should be(AutoGeneratedUsername.mtkClassDefault)
        values._2 should be(AutoGeneratedUsername.automaticGeneration)
      }
    }
  }
}

