version: 0.2

env:
  variables:
    batchMode: "true"
    awsConnectionEnabled: "false"

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - export CODE_ARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain digiroad --domain-owner 475079312496 --region eu-west-1 --query authorizationToken --output text)
      - aws codeartifact login --tool npm --repository digiroad_npm_packages --domain digiroad --domain-owner 475079312496
      - aws s3 cp s3://sbt-repository/sbt-0.13.18.deb /tmp/sbt-0.13.18.deb
      - sudo dpkg -i /tmp/sbt-0.13.18.deb
      - sudo apt-get install sbt
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - npm install -g yarn
      - yarn install --ignore-engines --production
      - npm install -g grunt-cli
  pre_build:
    commands:
      - pip install --upgrade awscli
      - rm conf/env.properties
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - grunt test
      - sbt "project digiroad2-oracle" "run-main fi.liikennevirasto.digiroad2.util.DataFixture test"
      - sbt test
      - grunt deploy
      - sbt clean
      - sbt assembly
      - docker build -f aws/fargate/Dockerfile --build-arg image=public.ecr.aws/docker/library/amazoncorretto:8-alpine-jre  -t $ECR_REPOSITORY_NAME:latest .
      - echo Post-build started on `date`
      - docker tag $ECR_REPOSITORY_NAME:latest $ECR_REPOSITORY_URI:latest
      - docker tag $ECR_REPOSITORY_NAME:latest $ECR_REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - docker tag $ECR_REPOSITORY_NAME:latest $ECR_REPOSITORY_URI:$COMMIT_HASH
  post_build:
    commands:
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_SERVICE_NAME $ECR_REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json