version: 0.2

env:
  variables:
    batchMode: "true"
    awsConnectionEnabled: "false"

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a  /etc/apt/sources.list.d/sbt.list
      - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update
      - apt-get install sbt
      - npm install -g yarn
      - npm install && yarn install --ignore-engines
      - npm install -g grunt-cli
  pre_build:
    commands:
      - pip install --upgrade awscli
      - $(aws ecr get-login --no-include-email --region eu-west-1)
      - mkdir digiroad2-geo/lib
      - aws s3 cp "s3://geotools-repo/gt-graph-19.0.jar" ./digiroad2-geo/lib
      - aws s3 cp "s3://geotools-repo/gt-main-19.0.jar" ./digiroad2-geo/lib
      - aws s3 cp "s3://geotools-repo/gt-api-19.0.jar" ./digiroad2-geo/lib
      - aws s3 cp "s3://geotools-repo/gt-referencing-19.0.jar" ./digiroad2-geo/lib
      - aws s3 cp "s3://geotools-repo/gt-metadata-19.0.jar" ./digiroad2-geo/lib
      - aws s3 cp "s3://geotools-repo/gt-opengis-19.0.jar" ./digiroad2-geo/lib
      - aws s3 cp "s3://geotools-repo/jts-core-1.14.0.jar" ./digiroad2-geo/lib
      - rm conf/env.properties
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - grunt deploy
      - sbt clean
      - sbt assembly
      - docker build -f aws/fargate/Dockerfile --build-arg image=public.ecr.aws/docker/library/amazoncorretto:8-alpine-jre  -t $ECR_REPOSITORY_NAME:latest .
      - echo Post-build started on `date`
      - docker tag $ECR_REPOSITORY_NAME:latest $ECR_REPOSITORY_URI:test
      - docker tag $ECR_REPOSITORY_NAME:latest $ECR_REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - docker tag $ECR_REPOSITORY_NAME:latest $ECR_REPOSITORY_URI:$COMMIT_HASH
      - docker push $ECR_REPOSITORY_URI:test
      - docker push $ECR_REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - docker push $ECR_REPOSITORY_URI:$COMMIT_HASH
  post_build:
    commands:
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_SERVICE_NAME $ECR_REPOSITORY_URI:test > imagedefinitions.json
artifacts:
  files: imagedefinitions.json