--modifications to state
UPDATE ENUMERATED_VALUE
SET NAME_FI = 'Käytössä pysyvästi'
WHERE NAME_FI = 'Toteutuma' AND PROPERTY_ID = (SELECT ID FROM PROPERTY p WHERE p.ASSET_TYPE_ID = 300 AND p.PUBLIC_ID = 'life_cycle');

UPDATE ENUMERATED_VALUE
SET VALUE = 6
WHERE VALUE = 99 AND PROPERTY_ID = (SELECT ID FROM PROPERTY p WHERE p.ASSET_TYPE_ID = 300 AND p.PUBLIC_ID = 'life_cycle');

--TrafficSigns modifications
UPDATE ENUMERATED_VALUE
SET VALUE = 99
WHERE VALUE = 999 AND PROPERTY_ID IN (SELECT ID FROM PROPERTY p WHERE p.ASSET_TYPE_ID = 300 AND p.PROPERTY_TYPE = 'single_choice');

--modifications in structure
UPDATE ENUMERATED_VALUE
SET NAME_FI = 'Pylväs'
WHERE NAME_FI = 'Tolppa' AND PROPERTY_ID = (SELECT ID FROM PROPERTY p WHERE p.ASSET_TYPE_ID = 300 AND p.PUBLIC_ID = 'structure');

UPDATE ENUMERATED_VALUE
SET VALUE = 7
WHERE VALUE = 6 AND PROPERTY_ID = (SELECT ID FROM PROPERTY p WHERE p.ASSET_TYPE_ID = 300 AND p.PUBLIC_ID = 'structure');

UPDATE ENUMERATED_VALUE
SET VALUE = 6
WHERE VALUE = 5 AND PROPERTY_ID = (SELECT ID FROM PROPERTY p WHERE p.ASSET_TYPE_ID = 300 AND p.PUBLIC_ID = 'structure');

INSERT INTO ENUMERATED_VALUE (ID, VALUE, NAME_FI, NAME_SV, CREATED_BY, PROPERTY_ID)
VALUES (primary_key_seq.nextval, 5, 'Puoliportaali', ' ', 'db_migration_v226', (select id from property where public_ID = 'structure'));