alter table property add public_id varchar(256) unique;
update property set public_id = 'matkustajatunnus' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Matkustajatunnus');
update property set public_id = 'nimi_suomeksi' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Nimi suomeksi');
update property set public_id = 'liikennointisuunta' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Liikennöintisuunta');
update property set public_id = 'katos' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Katos');
update property set public_id = 'pysakin_tyyppi' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Pysäkin tyyppi');
update property set public_id = 'tietojen_yllapitaja' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Tietojen ylläpitäjä');
update property set public_id = 'yllapitajan_tunnus' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Ylläpitäjän tunnus');
update property set public_id = 'palauteosoite' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Palauteosoite');
update property set public_id = 'esteettomyys_liikuntarajoitteiselle' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Esteettömyys liikuntarajoitteiselle');
update property set public_id = 'lisatiedot' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Lisätiedot');
update property set public_id = 'nimi_ruotsiksi' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Nimi ruotsiksi');
update property set public_id = 'maastokoordinaatti_x' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Maastokoordinaatti X');
update property set public_id = 'maastokoordinaatti_y' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Maastokoordinaatti Y');
update property set public_id = 'maastokoordinaatti_z' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Maastokoordinaatti Z');
update property set public_id = 'liikennointisuuntima' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Liikennöintisuuntima');
update property set public_id = 'aikataulu' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Aikataulu');
update property set public_id = 'mainoskatos' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Mainoskatos');
update property set public_id = 'penkki' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Penkki');
update property set public_id = 'pyorateline' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Pyöräteline');
update property set public_id = 'sahkoinen_aikataulunaytto' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Sähköinen aikataulunäyttö');
update property set public_id = 'valaistus' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Valaistus');
update property set public_id = 'saattomahdollisuus_henkiloautolla' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Saattomahdollisuus henkilöautolla');
update property set public_id = 'liityntapysakointipaikkojen_maara' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Liityntäpysäköintipaikkojen määrä');
update property set public_id = 'pysakin_omistaja' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Pysäkin omistaja');
update property set public_id = 'liityntapysakoinnin_lisatiedot' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Liityntäpysäköinnin lisätiedot');
update property set public_id = 'yllapitajan_koodi' where id = (select p.id from property p, localized_string ls where p.name_localized_string_id = ls.id and ls.value_fi = 'Ylläpitäjän koodi');
