
--Delete TEXT_PROPERTY_VALUE related with the fields to be deleted on old maintenance road assets
DELETE TEXT_PROPERTY_VALUE WHERE PROPERTY_ID = (SELECT ID FROM PROPERTY WHERE PUBLIC_ID = 'huoltotie_nimi');
DELETE TEXT_PROPERTY_VALUE WHERE PROPERTY_ID = (SELECT ID FROM PROPERTY WHERE PUBLIC_ID = 'huoltotie_osoite');
DELETE TEXT_PROPERTY_VALUE WHERE PROPERTY_ID = (SELECT ID FROM PROPERTY WHERE PUBLIC_ID = 'huoltotie_postinumero');
DELETE TEXT_PROPERTY_VALUE WHERE PROPERTY_ID = (SELECT ID FROM PROPERTY WHERE PUBLIC_ID = 'huoltotie_postitoimipaikka');
DELETE TEXT_PROPERTY_VALUE WHERE PROPERTY_ID = (SELECT ID FROM PROPERTY WHERE PUBLIC_ID = 'huoltotie_puh1');
DELETE TEXT_PROPERTY_VALUE WHERE PROPERTY_ID = (SELECT ID FROM PROPERTY WHERE PUBLIC_ID = 'huoltotie_puh2');
DELETE TEXT_PROPERTY_VALUE WHERE PROPERTY_ID = (SELECT ID FROM PROPERTY WHERE PUBLIC_ID = 'huoltotie_lisatieto');


--Delete unnecessary properties of maintenanceRoad asset
DELETE PROPERTY WHERE PUBLIC_ID = 'huoltotie_nimi' AND ASSET_TYPE_ID = 290;
DELETE PROPERTY WHERE PUBLIC_ID = 'huoltotie_osoite' AND ASSET_TYPE_ID = 290;
DELETE PROPERTY WHERE PUBLIC_ID = 'huoltotie_postinumero' AND ASSET_TYPE_ID = 290;
DELETE PROPERTY WHERE PUBLIC_ID = 'huoltotie_postitoimipaikka' AND ASSET_TYPE_ID = 290;
DELETE PROPERTY WHERE PUBLIC_ID = 'huoltotie_puh1' AND ASSET_TYPE_ID = 290;
DELETE PROPERTY WHERE PUBLIC_ID = 'huoltotie_puh2' AND ASSET_TYPE_ID = 290;
DELETE PROPERTY WHERE PUBLIC_ID = 'huoltotie_lisatieto' AND ASSET_TYPE_ID = 290;


--Delete unnecessary properties of maintenanceRoad asset
DELETE LOCALIZED_STRING WHERE VALUE_FI = 'Nimi';
DELETE LOCALIZED_STRING WHERE VALUE_FI = 'Osoite';
DELETE LOCALIZED_STRING WHERE VALUE_FI = 'Postinumero';
DELETE LOCALIZED_STRING WHERE VALUE_FI = 'Postitoimipaikka';
DELETE LOCALIZED_STRING WHERE VALUE_FI = 'Puhelin 1';
DELETE LOCALIZED_STRING WHERE VALUE_FI = 'Puhelin 2';
DELETE LOCALIZED_STRING WHERE VALUE_FI = 'Lisätietoa';