CREATE INDEX ENUMVALUE_PROPERTY_ID_IDX ON ENUMERATED_VALUE(PROPERTY_ID);
CREATE INDEX NUMPROPVAL_ASSET_PROP_ID_IDX ON NUMBER_PROPERTY_VALUE(ASSET_ID,PROPERTY_ID);
CREATE INDEX NUMPROPVAL_PROP_ID_IDX ON NUMBER_PROPERTY_VALUE(PROPERTY_ID);
CREATE INDEX PROPERTY_ASSETTYPE_ID_IDX ON PROPERTY(ASSET_TYPE_ID);