AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda for local testing purposes

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda for fetching road link changes, saving them and generating change sets
      MemorySize: 128
      Timeout: 30
      PackageType: Image
      ImageConfig:
        Command:
          - index.handler
      Environment:
        Variables:
          CHANGES_SINCE: ""
          CHANGES_UNTIL: ""
          CHANGE_BUCKET: ""
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ../../
      Dockerfile: Dockerfile