
ALTER TABLE additional_panel ADD CONSTRAINT sys_c003961017 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE additional_panel ADD CONSTRAINT sys_c003961018 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE additional_panel_history ADD CONSTRAINT sys_c003961118 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE additional_panel_history ADD CONSTRAINT sys_c003961119 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE asset ADD CONSTRAINT sys_c003960718 FOREIGN KEY (asset_type_id) REFERENCES asset_type(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE asset_history ADD CONSTRAINT sys_c003961106 FOREIGN KEY (asset_type_id) REFERENCES asset_type(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE asset_link ADD CONSTRAINT sys_c003960765 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE asset_link ADD CONSTRAINT sys_c003960766 FOREIGN KEY (position_id) REFERENCES lrm_position(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE asset_link_history ADD CONSTRAINT sys_c003961170 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE asset_link_history ADD CONSTRAINT sys_c003961171 FOREIGN KEY (position_id) REFERENCES lrm_position_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE connected_asset ADD CONSTRAINT sys_c003961022 FOREIGN KEY (linear_asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE connected_asset ADD CONSTRAINT sys_c003961023 FOREIGN KEY (point_asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dashboard_info ADD CONSTRAINT sys_c003961067 FOREIGN KEY (municipality_id) REFERENCES municipality(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE date_period_value ADD CONSTRAINT sys_c003961031 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE date_period_value ADD CONSTRAINT sys_c003961032 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE date_period_value_history ADD CONSTRAINT sys_c003961112 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE date_period_value_history ADD CONSTRAINT sys_c003961113 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE date_property_value ADD CONSTRAINT sys_c003960987 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE date_property_value ADD CONSTRAINT sys_c003960988 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE date_property_value_history ADD CONSTRAINT sys_c003961135 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE date_property_value_history ADD CONSTRAINT sys_c003961136 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE enumerated_value ADD CONSTRAINT sys_c003960738 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE inaccurate_asset ADD CONSTRAINT fk_asset_id FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE inaccurate_asset ADD CONSTRAINT fk_asset_type_id FOREIGN KEY (asset_type_id) REFERENCES asset_type(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE lane_attribute ADD CONSTRAINT fk_lane_attribute_lane FOREIGN KEY (lane_id) REFERENCES lane(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE lane_history_attribute ADD CONSTRAINT fk_l_hist_attrib_lane_hist FOREIGN KEY (lane_history_id) REFERENCES lane_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE lane_history_link ADD CONSTRAINT fk_l_hist_link_lane_history FOREIGN KEY (lane_id) REFERENCES lane_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE lane_history_link ADD CONSTRAINT fk_l_hist_link_lane_hist_pos FOREIGN KEY (lane_position_id) REFERENCES lane_history_position(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE lane_link ADD CONSTRAINT fk_lane_link_lane FOREIGN KEY (lane_id) REFERENCES lane(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE lane_link ADD CONSTRAINT fk_lane_link_lane_position FOREIGN KEY (lane_position_id) REFERENCES lane_position(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE manoeuvre ADD CONSTRAINT fk_traffic_sign_id FOREIGN KEY (traffic_sign_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE manoeuvre_element ADD CONSTRAINT sys_c003960796 FOREIGN KEY (manoeuvre_id) REFERENCES manoeuvre(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE manoeuvre_element_history ADD CONSTRAINT sys_c003961204 FOREIGN KEY (manoeuvre_id) REFERENCES manoeuvre_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE manoeuvre_exceptions ADD CONSTRAINT manoeuvre_fk FOREIGN KEY (manoeuvre_id) REFERENCES manoeuvre(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE manoeuvre_exceptions_history ADD CONSTRAINT hist_manoeuvre_fk FOREIGN KEY (manoeuvre_id) REFERENCES manoeuvre_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE manoeuvre_validity_period ADD CONSTRAINT sys_c003960831 FOREIGN KEY (manoeuvre_id) REFERENCES manoeuvre(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE manoeuvre_val_period_history ADD CONSTRAINT sys_c003961214 FOREIGN KEY (manoeuvre_id) REFERENCES manoeuvre_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE multiple_choice_value ADD CONSTRAINT sys_c003960750 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE multiple_choice_value ADD CONSTRAINT sys_c003960751 FOREIGN KEY (enumerated_value_id) REFERENCES enumerated_value(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE multiple_choice_value ADD CONSTRAINT sys_c003960752 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE multiple_choice_value_history ADD CONSTRAINT sys_c003961151 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE multiple_choice_value_history ADD CONSTRAINT sys_c003961152 FOREIGN KEY (enumerated_value_id) REFERENCES enumerated_value(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE multiple_choice_value_history ADD CONSTRAINT sys_c003961153 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE municipality_feature ADD CONSTRAINT sys_c003961062 FOREIGN KEY (dataset_id) REFERENCES municipality_dataset(dataset_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE municipality_verification ADD CONSTRAINT sys_c003960976 FOREIGN KEY (municipality_id) REFERENCES municipality(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE municipality_verification ADD CONSTRAINT sys_c003960977 FOREIGN KEY (asset_type_id) REFERENCES asset_type(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE number_property_value ADD CONSTRAINT sys_c003960774 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE number_property_value ADD CONSTRAINT sys_c003960775 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE number_property_value_history ADD CONSTRAINT sys_c003961145 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE number_property_value_history ADD CONSTRAINT sys_c003961146 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prohibition_exception ADD CONSTRAINT sys_c003960815 FOREIGN KEY (prohibition_value_id) REFERENCES prohibition_value(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prohibition_exception_history ADD CONSTRAINT sys_c003961179 FOREIGN KEY (prohibition_value_id) REFERENCES prohibition_value_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prohibition_validity_period ADD CONSTRAINT sys_c003960823 FOREIGN KEY (prohibition_value_id) REFERENCES prohibition_value(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prohibition_value ADD CONSTRAINT sys_c003960811 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE prohibition_value_history ADD CONSTRAINT sys_c003961175 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE proh_val_period_history ADD CONSTRAINT sys_c003961189 FOREIGN KEY (prohibition_value_id) REFERENCES prohibition_value_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE property ADD CONSTRAINT fk_prop_name_localized FOREIGN KEY (name_localized_string_id) REFERENCES localized_string(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE property ADD CONSTRAINT sys_c003960725 FOREIGN KEY (asset_type_id) REFERENCES asset_type(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE service_point_value ADD CONSTRAINT sys_c003960836 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE service_point_value_history ADD CONSTRAINT sys_c003961141 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE single_choice_value ADD CONSTRAINT sys_c003960743 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE single_choice_value ADD CONSTRAINT sys_c003960744 FOREIGN KEY (enumerated_value_id) REFERENCES enumerated_value(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE single_choice_value ADD CONSTRAINT sys_c003960745 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE single_choice_value_history ADD CONSTRAINT sys_c003961157 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE single_choice_value_history ADD CONSTRAINT sys_c003961158 FOREIGN KEY (enumerated_value_id) REFERENCES enumerated_value(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE single_choice_value_history ADD CONSTRAINT sys_c003961159 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE terminal_bus_stop_link ADD CONSTRAINT sys_c003960943 FOREIGN KEY (terminal_asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE terminal_bus_stop_link ADD CONSTRAINT sys_c003960944 FOREIGN KEY (bus_stop_asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE text_property_value ADD CONSTRAINT sys_c003960730 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE text_property_value ADD CONSTRAINT sys_c003960731 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE text_property_value_history ADD CONSTRAINT sys_c003961164 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE text_property_value_history ADD CONSTRAINT sys_c003961165 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE traffic_sign_manager ADD CONSTRAINT fk_linear_asset_type_id FOREIGN KEY (linear_asset_type_id) REFERENCES asset_type(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE traffic_sign_manager ADD CONSTRAINT fk_m_traffic_sign_id FOREIGN KEY (traffic_sign_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE validity_period_property_value ADD CONSTRAINT sys_c003960999 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE validity_period_property_value ADD CONSTRAINT sys_c003961000 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vallu_xml_ids ADD CONSTRAINT sys_c003961055 FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE val_period_property_value_hist ADD CONSTRAINT sys_c003961129 FOREIGN KEY (asset_id) REFERENCES asset_history(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE val_period_property_value_hist ADD CONSTRAINT sys_c003961130 FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
