
CREATE SEQUENCE grouped_id_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1 CACHE 100;
CREATE SEQUENCE lrm_position_primary_key_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 40000000 CACHE 100 CYCLE;
CREATE SEQUENCE manoeuvre_id_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 200000 CACHE 100 CYCLE;
CREATE SEQUENCE national_bus_stop_id_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 300000 CACHE 100;
CREATE SEQUENCE primary_key_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 300000 CACHE 100 CYCLE;
CREATE SEQUENCE user_notification_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 4;