Alter Table ROAD_ADDRESS_CHANGES Modify (OLD_TRACK_CODE NULL);
Alter Table ROAD_ADDRESS_CHANGES Modify (OLD_ROAD_PART_NUMBER NULL);
Alter Table ROAD_ADDRESS_CHANGES Modify (OLD_ROAD_NUMBER NULL);
Alter Table ROAD_ADDRESS_CHANGES Modify (OLD_END_ADDR_M NULL);
Alter Table ROAD_ADDRESS_CHANGES Modify (OLD_START_ADDR_M NULL);

Alter Table ROAD_ADDRESS_CHANGES Modify (NEW_TRACK_CODE NULL);
Alter Table ROAD_ADDRESS_CHANGES Modify (NEW_ROAD_PART_NUMBER NULL);
Alter Table ROAD_ADDRESS_CHANGES Modify (NEW_ROAD_NUMBER NULL);
Alter Table ROAD_ADDRESS_CHANGES Modify (NEW_END_ADDR_M NULL);
Alter Table ROAD_ADDRESS_CHANGES Modify (NEW_START_ADDR_M NULL);
