ALTER TABLE ROAD_ADDRESS
  ADD TERMINATED NUMBER DEFAULT 0 NOT NULL
  ADD CONSTRAINT BOOLEAN_TERMINATED CHECK (TERMINATED IN (0,1))
  ADD CONSTRANT VALID_TERMINATION CHECK (TERMINATED = 0 AND END_DATE IS NOT NULL);
