ALTER TABLE ROAD_ADDRESS
  ADD TERMINATED NUMBER DEFAULT 0 NOT NULL
  ADD CONSTRAINT BOOLEAN_TERMINATED CHECK (TERMINATED IN (0,1));

CREATE OR REPLACE TRIGGER VALID_TERMINATION
BEFORE INSERT OR UPDATE
  ON ROAD_ADDRESS
  FOR EACH ROW
BEGIN
  IF :NEW.TERMINATED = 1 AND :NEW.END_DATE IS NULL
  THEN
    RAISE_APPLICATION_ERROR(-20000, 'Cannot assign value 1 to terminated without a END_DATE being defined.');
  END IF;
END;