ALTER TABLE ROAD_ADDRESS
  ADD TERMINATED NUMBER DEFAULT 0 NOT NULL
  ADD CONSTRAINT BOOLEAN_TERMINATED CHECK (TERMINATED IN (0,1));

  /*ADD CONSTRANT VALID_TERMINATION CHECK (TERMINATED = 0 AND END_DATE IS NOT NULL);

   */

CREATE OR REPLACE TRIGGER VALID_TERMINATION
BEFORE INSERT OR UPDATE
  ON ROAD_ADDRESS
  FOR EACH ROW
BEGIN
  DBMS_OUTPUT.Put_Line('Starting VALID_TERMINATION');
  IF :NEW.TERMINATED = 1 AND :NEW.END_DATE IS NULL
  THEN
  DBMS_OUTPUT.Put_Line('Will Return error');
    RAISE_APPLICATION_ERROR(-20000, 'Cannot assign value 1 to terminated without a END_DATE being defined.');
  ELSE
    DBMS_OUTPUT.Put_Line('NO Error');
  END IF;
  DBMS_OUTPUT.Put_Line('Ending VALID_TERMINATION');
END;