ALTER TABLE ROAD_ADDRESS
  ADD TERMINATED NUMBER DEFAULT 0 NOT NULL;

ALTER TABLE ROAD_ADDRESS
  ADD CONSTRAINT CK_TERMINATION_END_DATE CHECK (TERMINATED = 0 OR (TERMINATED = 1 AND END_DATE IS NOT NULL));
