ALTER TABLE PROJECT_RESERVED_ROAD_PART DROP COLUMN ROAD_LENGTH;
ALTER TABLE PROJECT_RESERVED_ROAD_PART DROP COLUMN FIRST_LINK_ID;
ALTER TABLE PROJECT_RESERVED_ROAD_PART DROP COLUMN ADDRESS_LENGTH;
ALTER TABLE PROJECT_RESERVED_ROAD_PART DROP COLUMN DISCONTINUITY;
ALTER TABLE PROJECT_RESERVED_ROAD_PART DROP COLUMN ELY;
