CREATE TABLE INACCURATE_ASSET
(
   ASSET_ID        NUMBER NOT NULL,
   ASSET_TYPE_ID   NUMBER NOT NULL,
   CREATED_DATE    TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
   CONSTRAINT FK_ASSET_ID FOREIGN KEY (ASSET_ID) REFERENCES ASSET (ID),
   CONSTRAINT FK_ASSET_TYPE_ID FOREIGN KEY (ASSET_TYPE_ID) REFERENCES ASSET_TYPE (ID)
);

CREATE INDEX INACCURATE_ASSET_ID_IDX
   ON INACCURATE_ASSET (ASSET_ID);

CREATE INDEX INACCURATE_ASSET_ID_TYPE_IDX
   ON INACCURATE_ASSET (ASSET_ID, ASSET_TYPE_ID);