CREATE TABLE INACCURATE_ASSET
(
   ASSET_ID        NUMBER NOT NULL,
   ASSET_TYPE_ID   NUMBER NOT NULL,
   MUNICIPALITY_CODE     NUMBER(5),
   ADMINISTRATIVE_CLASS  NUMBER(3),
   CREATED_DATE    TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
   CONSTRAINT FK_ASSET_ID FOREIGN KEY (ASSET_ID) REFERENCES ASSET (ID),
   CONSTRAINT FK_ASSET_TYPE_ID FOREIGN KEY (ASSET_TYPE_ID) REFERENCES ASSET_TYPE (ID)
);

CREATE INDEX INACCURATE_ASSET_ID_IDX
   ON INACCURATE_ASSET (ASSET_ID);

CREATE INDEX INACCURATE_ASSET_TYPE_ID_IDX
   ON INACCURATE_ASSET (ASSET_TYPE_ID);

CREATE INDEX INACCURATE_ASSET_ALL_INFO_IDX
   ON INACCURATE_ASSET (ASSET_TYPE_ID, MUNICIPALITY_CODE, ADMINISTRATIVE_CLASS);