ALTER TABLE MUNICIPALITY_FEATURE
ADD FEATURE_ID_TEMP VARCHAR2(4000);

UPDATE MUNICIPALITY_FEATURE SET FEATURE_ID_TEMP = FEATURE_ID;

ALTER TABLE MUNICIPALITY_FEATURE
DROP CONSTRAINT PK_MUNICIPALITY_FEATURE;

ALTER TABLE MUNICIPALITY_FEATURE
ADD CONSTRAINT PK_MUNICIPALITY_FEATURE PRIMARY KEY(FEATURE_ID_TEMP, DATASET_ID);

ALTER TABLE MUNICIPALITY_FEATURE
DROP COLUMN FEATURE_ID;

ALTER TABLE MUNICIPALITY_FEATURE
RENAME COLUMN FEATURE_ID_TEMP TO FEATURE_ID;