--Alter Constraints
ALTER TABLE SINGLE_CHOICE_VALUE
DROP CONSTRAINT SINGLE_CHOICE_PK;

COMMIT;

ALTER TABLE SINGLE_CHOICE_VALUE
ADD CONSTRAINT SINGLE_CHOICE_PK PRIMARY KEY (ASSET_ID, ENUMERATED_VALUE_ID, GROUPED_ID);

DROP INDEX AID_PID_TEXT_PROPERTY_SX;

CREATE UNIQUE INDEX AID_PID_TEXT_PROPERTY_SX ON TEXT_PROPERTY_VALUE ("ASSET_ID", "PROPERTY_ID", "GROUPED_ID");