--Alter Constraints
BEGIN
	  EXECUTE IMMEDIATE 'ALTER TABLE SINGLE_CHOICE_VALUE DROP CONSTRAINT SINGLE_CHOICE_PK';
    EXECUTE IMMEDIATE 'ALTER TABLE SINGLE_CHOICE_VALUE ADD CONSTRAINT SINGLE_CHOICE_PK PRIMARY KEY (ASSET_ID, ENUMERATED_VALUE_ID, GROUPED_ID)';

   	EXECUTE IMMEDIATE 'DROP INDEX AID_PID_TEXT_PROPERTY_SX';
   	EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX AID_PID_TEXT_PROPERTY_SX ON TEXT_PROPERTY_VALUE ("ASSET_ID", "PROPERTY_ID", "GROUPED_ID")';
END;