-- Create temporary table as auxiliary table
CREATE GLOBAL TEMPORARY TABLE tmp_signs (
    othId NUMBER,
	name  VARCHAR2(200)
)
ON COMMIT PRESERVE ROWS;


DECLARE
    v_property_id NUMBER;

BEGIN

    -- Insert the values into the temporary table
    Insert Into tmp_signs (othId, name) Values (36, 'A1.1 Mutka oikealle');
    Insert Into tmp_signs (othId, name) Values (37, 'A1.2 Mutka vasemmalle');
    Insert Into tmp_signs (othId, name) Values (38, 'A2.1 Mutkia, joista ensimmäinen oikealle');
    Insert Into tmp_signs (othId, name) Values (39, 'A2.2 Mutkia, joista ensimmäinen vasemmalle');
    Insert Into tmp_signs (othId, name) Values (41, 'A3.1 Jyrkkä ylämäki');
    Insert Into tmp_signs (othId, name) Values (40, 'A3.2 Jyrkkä alamäki');
    Insert Into tmp_signs (othId, name) Values (82, 'A4 Kapeneva tie');
    Insert Into tmp_signs (othId, name) Values (83, 'A5 Kaksisuuntainen liikenne');
    Insert Into tmp_signs (othId, name) Values (84, 'A6 Avattava silta');
    Insert Into tmp_signs (othId, name) Values (200, 'A7 Lautta, laituri tai ranta');
    Insert Into tmp_signs (othId, name) Values (201, 'A8 Liikenneruuhka');
    Insert Into tmp_signs (othId, name) Values (42, 'A9 Epätasainen tie');
    Insert Into tmp_signs (othId, name) Values (202, 'A10 Töyssyjä');
    Insert Into tmp_signs (othId, name) Values (85, 'A11 Tietyö');
    Insert Into tmp_signs (othId, name) Values (203, 'A12 Irtokiviä');
    Insert Into tmp_signs (othId, name) Values (86, 'A13 Liukas ajorata');
    Insert Into tmp_signs (othId, name) Values (204, 'A14 Vaarallinen tien reuna');
    Insert Into tmp_signs (othId, name) Values (87, 'A15 Suojatien ennakkovaroitus');
    Insert Into tmp_signs (othId, name) Values (205, 'A16 Jalankulkijoita');
    Insert Into tmp_signs (othId, name) Values (43, 'A17 Lapsia');
    Insert Into tmp_signs (othId, name) Values (88, 'A18 Pyöräilijöitä');
    Insert Into tmp_signs (othId, name) Values (206, 'A19 Hiihtolatu');
    Insert Into tmp_signs (othId, name) Values (125, 'A20.1 Hirvi');
    Insert Into tmp_signs (othId, name) Values (126, 'A20.2 Poro');
    Insert Into tmp_signs (othId, name) Values (207, 'A20.3 Kauriseläin');
    Insert Into tmp_signs (othId, name) Values (89, 'A21 Tienristeys');
    Insert Into tmp_signs (othId, name) Values (127, 'A22.1 Sivutien risteys molemmin puolin');
    Insert Into tmp_signs (othId, name) Values (208, 'A22.2 Sivutien risteys molemmin puolin porrastetusti');
    Insert Into tmp_signs (othId, name) Values (128, 'A22.3 Sivutien risteys oikealla/vasemmalla');
    Insert Into tmp_signs (othId, name) Values (129, 'A22.4 Sivutien risteys oikealla/vasemmalla viistoon');
    Insert Into tmp_signs (othId, name) Values (90, 'A23 Liikennevalot');
    Insert Into tmp_signs (othId, name) Values (209, 'A24 Liikenneympyrä');
    Insert Into tmp_signs (othId, name) Values (91, 'A25 Raitiovaunu');
    Insert Into tmp_signs (othId, name) Values (130, 'A26 Rautatien tasoristeys ilman puomeja');
    Insert Into tmp_signs (othId, name) Values (131, 'A27 Rautatien tasoristeys, jossa on puomit');
    Insert Into tmp_signs (othId, name) Values (210, 'A28.1 Rautatien tasoristeyksen lähestymismerkki');
    Insert Into tmp_signs (othId, name) Values (211, 'A28.2 Rautatien tasoristeyksen lähestymismerkki');
    Insert Into tmp_signs (othId, name) Values (212, 'A28.3 Rautatien tasoristeyksen lähestymismerkki');
    Insert Into tmp_signs (othId, name) Values (132, 'A29.1 Yksiraiteisen rautatien tasoristeys');
    Insert Into tmp_signs (othId, name) Values (133, 'A29.2 Kaksi tai useampiraiteisen rautatien tasoristeys');
    Insert Into tmp_signs (othId, name) Values (92, 'A30 Putoavia kiviä');
    Insert Into tmp_signs (othId, name) Values (213, 'A31 Matalalla lentäviä lentokoneita');
    Insert Into tmp_signs (othId, name) Values (93, 'A32 Sivutuuli');
    Insert Into tmp_signs (othId, name) Values (9, 'A33 Muu vaara');
    Insert Into tmp_signs (othId, name) Values (94, 'B1 Etuajo-oikeutettu tie');
    Insert Into tmp_signs (othId, name) Values (95, 'B2 Etuajo-oikeuden päättyminen');
    Insert Into tmp_signs (othId, name) Values (96, 'B3 Etuajo-oikeus kohdattaessa');
    Insert Into tmp_signs (othId, name) Values (97, 'B4 Väistämisvelvollisuus kohdattaessa');
    Insert Into tmp_signs (othId, name) Values (98, 'B5 Väistämisvelvollisuus risteyksessä');
    Insert Into tmp_signs (othId, name) Values (99, 'B6 Pakollinen pysäyttäminen');
    Insert Into tmp_signs (othId, name) Values (214, 'B7 Väistämisvelvollisuus pyöräilijän tienylityspaikassa');
    Insert Into tmp_signs (othId, name) Values (13, 'C1 Ajoneuvolla ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (14, 'C2 Moottorikäyttöisellä ajoneuvolla ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (15, 'C3 Kuorma- ja pakettiautolla ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (16, 'C4 Ajoneuvoyhdistelmällä ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (17, 'C5 Traktorilla ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (18, 'C6 Moottoripyörällä ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (19, 'C7 Moottorikelkalla ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (20, 'C8 Vaarallisten aineiden kuljetus kielletty');
    Insert Into tmp_signs (othId, name) Values (21, 'C9 Linja-autolla ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (22, 'C10 Mopolla ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (215, 'C11 Polkupyörällä ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (23, 'C12 Polkupyörällä ja mopolla ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (24, 'C13 Jalankulku kielletty');
    Insert Into tmp_signs (othId, name) Values (216, 'C14 Jalankulku ja polkupyörällä ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (25, 'C15 Jalankulku ja polkupyörällä ja mopolla ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (26, 'C16 Ratsastus kielletty');
    Insert Into tmp_signs (othId, name) Values (27, 'C17 Kielletty ajosuunta');
    Insert Into tmp_signs (othId, name) Values (10, 'C18 Vasemmalle kääntyminen kielletty');
    Insert Into tmp_signs (othId, name) Values (11, 'C19 Oikealle kääntyminen kielletty');
    Insert Into tmp_signs (othId, name) Values (12, 'C20 U-käännös kielletty');
    Insert Into tmp_signs (othId, name) Values (30, 'C21 Ajoneuvon suurin sallittu leveys');
    Insert Into tmp_signs (othId, name) Values (31, 'C22 Ajoneuvon suurin sallittu korkeus');
    Insert Into tmp_signs (othId, name) Values (8, 'C23 Ajoneuvon tai ajoneuvoyhdistelmän suurin sallittu pituus');
    Insert Into tmp_signs (othId, name) Values (32, 'C24 Ajoneuvon suurin sallittu massa');
    Insert Into tmp_signs (othId, name) Values (33, 'C25 Ajoneuvoyhdistelmän suurin sallittu massa');
    Insert Into tmp_signs (othId, name) Values (34, 'C26 Ajoneuvon suurin sallittu akselille kohdistuva massa');
    Insert Into tmp_signs (othId, name) Values (35, 'C27 Ajoneuvon suurin sallittu telille kohdistuva massa');
    Insert Into tmp_signs (othId, name) Values (28, 'C28 Ohituskielto');
    Insert Into tmp_signs (othId, name) Values (29, 'C29 Ohituskielto päättyy');
    Insert Into tmp_signs (othId, name) Values (217, 'C30 Ohituskielto kuorma-autolla');
    Insert Into tmp_signs (othId, name) Values (218, 'C31 Ohituskielto kuorma-autolla päättyy');
    Insert Into tmp_signs (othId, name) Values (1, 'C32 Nopeusrajoitus');
    Insert Into tmp_signs (othId, name) Values (2, 'C33 Nopeusrajoitus päättyy');
    Insert Into tmp_signs (othId, name) Values (3, 'C34 Nopeusrajoitusalue');
    Insert Into tmp_signs (othId, name) Values (4, 'C35 Nopeusrajoitusalue päättyy');
    Insert Into tmp_signs (othId, name) Values (219, 'C36 Ajokaistakohtainen kielto, rajoitus tai määräys');
    Insert Into tmp_signs (othId, name) Values (100, 'C37 Pysäyttäminen kielletty');
    Insert Into tmp_signs (othId, name) Values (101, 'C38 Pysäköinti kielletty');
    Insert Into tmp_signs (othId, name) Values (102, 'C39 Pysäköintikieltoalue');
    Insert Into tmp_signs (othId, name) Values (103, 'C40 Pysäköintikieltoalue päättyy');
    Insert Into tmp_signs (othId, name) Values (80, 'C41 Taksiasema-alue');
    Insert Into tmp_signs (othId, name) Values (81, 'C42 Taksin pysäyttämispaikka');
    Insert Into tmp_signs (othId, name) Values (220, 'C43 Kuormauspaikka');
    Insert Into tmp_signs (othId, name) Values (104, 'C44.1 Vuoropysäköinti (kielletty parittomina päivinä)');
    Insert Into tmp_signs (othId, name) Values (134, 'C44.2 Vuoropysäköinti (kielletty parillisina päivinä)');
    Insert Into tmp_signs (othId, name) Values (221, 'C45 Pakollinen pysäyttäminen tullitarkastusta varten');
    Insert Into tmp_signs (othId, name) Values (222, 'C46 Pakollinen pysäyttäminen tarkastusta varten');
    Insert Into tmp_signs (othId, name) Values (223, 'C47 Moottorikäyttöisten ajoneuvojen vähimmäisetäisyys');
    Insert Into tmp_signs (othId, name) Values (224, 'C48 Nastarenkailla varustetulla moottorikäyttöisellä ajoneuvolla ajo kielletty');
    Insert Into tmp_signs (othId, name) Values (225, 'D1.1 Pakollinen ajosuunta oikealle');
    Insert Into tmp_signs (othId, name) Values (226, 'D1.2 Pakollinen ajosuunta vasemmalle');
    Insert Into tmp_signs (othId, name) Values (227, 'D1.3 Pakollinen ajosuunta suoraan');
    Insert Into tmp_signs (othId, name) Values (74, 'D1.4 Pakollinen ajosuunta kääntyminen oikealle');
    Insert Into tmp_signs (othId, name) Values (228, 'D1.5 Pakollinen ajosuunta kääntyminen vasemmalle');
    Insert Into tmp_signs (othId, name) Values (229, 'D1.6 Pakollinen ajosuunta suoraan tai kääntyminen oikealle');
    Insert Into tmp_signs (othId, name) Values (230, 'D1.7 Pakollinen ajosuunta suoraan tai kääntyminen vasemmalle');
    Insert Into tmp_signs (othId, name) Values (231, 'D1.8 Pakollinen ajosuunta kääntyminen oikealle tai vasemmalle');
    Insert Into tmp_signs (othId, name) Values (232, 'D1.9 Pakollinen ajosuunta suoraan tai kääntyminen oikealle tai vasemmalle');
    Insert Into tmp_signs (othId, name) Values (77, 'D2 Pakollinen kiertosuunta');
    Insert Into tmp_signs (othId, name) Values (78, 'D3.1 Liikenteenjakaja oikea');
    Insert Into tmp_signs (othId, name) Values (233, 'D3.2 Liikenteenjakaja vasen');
    Insert Into tmp_signs (othId, name) Values (234, 'D3.3 Liikenteenjakaja molemmin puolin');
    Insert Into tmp_signs (othId, name) Values (70, 'D4 Jalkakäytävä');
    Insert Into tmp_signs (othId, name) Values (71, 'D5 Pyörätie');
    Insert Into tmp_signs (othId, name) Values (72, 'D6 Yhdistetty pyörätie ja jalkakäytävä');
    Insert Into tmp_signs (othId, name) Values (235, 'D7.1 Pyörätie ja jalkakäytävä rinnakkain, pyörätie vasemmalla');
    Insert Into tmp_signs (othId, name) Values (236, 'D7.2 Pyörätie ja jalkakäytävä rinnakkain, pyörätie oikealla');
    Insert Into tmp_signs (othId, name) Values (135, 'D8 Moottorikelkkailureitti');
    Insert Into tmp_signs (othId, name) Values (136, 'D9 Ratsastustie');
    Insert Into tmp_signs (othId, name) Values (237, 'D10 Vähimmäisnopeus');
    Insert Into tmp_signs (othId, name) Values (238, 'D11 Vähimmäisnopeus päättyy');
    Insert Into tmp_signs (othId, name) Values (7, 'E1 Suojatie');
    Insert Into tmp_signs (othId, name) Values (105, 'E2 Pysäköintipaikka');
    Insert Into tmp_signs (othId, name) Values (137, 'E3.1 Liityntäpysäköintipaikka juna');
    Insert Into tmp_signs (othId, name) Values (239, 'E3.2 Liityntäpysäköintipaikka bussi');
    Insert Into tmp_signs (othId, name) Values (240, 'E3.3 Liityntäpysäköintipaikka tram');
    Insert Into tmp_signs (othId, name) Values (241, 'E3.4 Liityntäpysäköintipaikka metro');
    Insert Into tmp_signs (othId, name) Values (242, 'E3.5 Liityntäpysäköintipaikka useita joukkoliikennevälineitä');
    Insert Into tmp_signs (othId, name) Values (243, 'E4.1 Ajoneuvojen sijoitus pysäköintipaikalla suoraan');
    Insert Into tmp_signs (othId, name) Values (244, 'E4.2 Ajoneuvojen sijoitus pysäköintipaikalla vastakkain');
    Insert Into tmp_signs (othId, name) Values (245, 'E4.3 Ajoneuvojen sijoitus pysäköintipaikalla vinoon');
    Insert Into tmp_signs (othId, name) Values (246, 'E5 Kohtaamispaikka');
    Insert Into tmp_signs (othId, name) Values (66, 'E6 Linja-autopysäkki');
    Insert Into tmp_signs (othId, name) Values (247, 'E6 Linja-autopysäkki');
    Insert Into tmp_signs (othId, name) Values (68, 'E7 Raitiovaunupysäkki');
    Insert Into tmp_signs (othId, name) Values (69, 'E8 Taksiasema');
    Insert Into tmp_signs (othId, name) Values (63, 'E9.1 Linja-autokaista');
    Insert Into tmp_signs (othId, name) Values (248, 'E9.2 Linja-auto ja taksikaista');
    Insert Into tmp_signs (othId, name) Values (64, 'E10.1 Linja-autokaista päättyy');
    Insert Into tmp_signs (othId, name) Values (249, 'E10.2 Linja-auto ja taksikaista päättyy');
    Insert Into tmp_signs (othId, name) Values (65, 'E11.1 Raitiovaunukaista');
    Insert Into tmp_signs (othId, name) Values (250, 'E11.2 Raitiovaunu- ja taksikaista');
    Insert Into tmp_signs (othId, name) Values (251, 'E12.1 Raitiovaunukaista päättyy');
    Insert Into tmp_signs (othId, name) Values (252, 'E12.2 Raitiovaunu- ja taksikaista päättyy');
    Insert Into tmp_signs (othId, name) Values (253, 'E13.1 Pyöräkaista oikealla');
    Insert Into tmp_signs (othId, name) Values (254, 'E13.2 Pyöräkaista keskellä');
    Insert Into tmp_signs (othId, name) Values (106, 'E14.1 Yksisuuntainen tie suoraan');
    Insert Into tmp_signs (othId, name) Values (255, 'E14.2 Yksisuuntainen tie oikealle/vasemmalle');
    Insert Into tmp_signs (othId, name) Values (107, 'E15 Moottoritie');
    Insert Into tmp_signs (othId, name) Values (108, 'E16 Moottoritie päättyy');
    Insert Into tmp_signs (othId, name) Values (256, 'E17 Moottoriliikennetie');
    Insert Into tmp_signs (othId, name) Values (257, 'E18 Moottoriliikennetie päättyy');
    Insert Into tmp_signs (othId, name) Values (258, 'E19 Tunneli');
    Insert Into tmp_signs (othId, name) Values (259, 'E20 Tunneli päättyy');
    Insert Into tmp_signs (othId, name) Values (260, 'E21 Hätäpysäyttämispaikka');
    Insert Into tmp_signs (othId, name) Values (5, 'E22 Taajama');
    Insert Into tmp_signs (othId, name) Values (6, 'E23 Taajama päättyy');
    Insert Into tmp_signs (othId, name) Values (109, 'E24 Pihakatu');
    Insert Into tmp_signs (othId, name) Values (110, 'E25 Pihakatu päättyy');
    Insert Into tmp_signs (othId, name) Values (111, 'E26 Kävelykatu');
    Insert Into tmp_signs (othId, name) Values (112, 'E27 Kävelykatu päättyy');
    Insert Into tmp_signs (othId, name) Values (261, 'E28 Pyöräkatu');
    Insert Into tmp_signs (othId, name) Values (262, 'E29 Pyöräkatu päättyy');
    Insert Into tmp_signs (othId, name) Values (263, 'E30 Ajokaistojen yhdistymien');
    Insert Into tmp_signs (othId, name) Values (192, 'F1.1 Suunnistustaulu');
    Insert Into tmp_signs (othId, name) Values (264, 'F1.2 Suunnistustaulu');
    Insert Into tmp_signs (othId, name) Values (265, 'F1.3 Suunnistustaulu');
    Insert Into tmp_signs (othId, name) Values (178, 'F2.1 Suunnistustaulu');
    Insert Into tmp_signs (othId, name) Values (266, 'F2.2 Suunnistustaulu');
    Insert Into tmp_signs (othId, name) Values (267, 'F2.3 Suunnistustaulu');
    Insert Into tmp_signs (othId, name) Values (268, 'F3 Ajokaistakohtainen suunnistustaulu');
    Insert Into tmp_signs (othId, name) Values (152, 'F4.1 Kiertotien suunnistustaulu (sininen pohja)');
    Insert Into tmp_signs (othId, name) Values (193, 'F4.2 Kiertotien suunnistustaulu (keltainen pohja)');
    Insert Into tmp_signs (othId, name) Values (153, 'F5 Kiertotieopastus');
    Insert Into tmp_signs (othId, name) Values (154, 'F6 Ajoreittiopastus');
    Insert Into tmp_signs (othId, name) Values (155, 'F7.1 Ajokaistaopastus');
    Insert Into tmp_signs (othId, name) Values (156, 'F7.2 Ajokaistaopastus');
    Insert Into tmp_signs (othId, name) Values (269, 'F7.3 Ajokaistaopastus');
    Insert Into tmp_signs (othId, name) Values (270, 'F7.4 Ajokaistaopastus');
    Insert Into tmp_signs (othId, name) Values (271, 'F7.5 Ajokaistaopastus');
    Insert Into tmp_signs (othId, name) Values (272, 'F7.6 Ajokaistaopastus');
    Insert Into tmp_signs (othId, name) Values (157, 'F8.1 Ajokaistan päättyminen');
    Insert Into tmp_signs (othId, name) Values (399, 'F8.2 Ajokaistan päättyminen');
    Insert Into tmp_signs (othId, name) Values (273, 'F9 Viitoituksen koontimerkki');
    Insert Into tmp_signs (othId, name) Values (158, 'F10 Ajokaistan yläpuolinen viitta');
    Insert Into tmp_signs (othId, name) Values (191, 'F11 Ajokaistan yläpuolinen viitta');
    Insert Into tmp_signs (othId, name) Values (159, 'F12 Ajokaistan yläpuolinen erkanemisviitta');
    Insert Into tmp_signs (othId, name) Values (160, 'F13 Tienviitta');
    Insert Into tmp_signs (othId, name) Values (162, 'F13 Tienviitta');
    Insert Into tmp_signs (othId, name) Values (167, 'F13 Tienviitta');
    Insert Into tmp_signs (othId, name) Values (168, 'F13 Tienviitta');
    Insert Into tmp_signs (othId, name) Values (161, 'F14 Erkanemisviitta');
    Insert Into tmp_signs (othId, name) Values (165, 'F15 Kiertotien viitta');
    Insert Into tmp_signs (othId, name) Values (166, 'F15 Kiertotien viitta');
    Insert Into tmp_signs (othId, name) Values (274, 'F15 Kiertotien viitta');
    Insert Into tmp_signs (othId, name) Values (163, 'F16 Osoiteviitta');
    Insert Into tmp_signs (othId, name) Values (275, 'F17 Osoiteviitan ennakkomerkki');
    Insert Into tmp_signs (othId, name) Values (169, 'F18.1 Liityntäpysäköintiviitta juna');
    Insert Into tmp_signs (othId, name) Values (276, 'F18.2 Liityntäpysäköintiviitta bussi');
    Insert Into tmp_signs (othId, name) Values (277, 'F18.3 Liityntäpysäköintiviitta raitiovaunu');
    Insert Into tmp_signs (othId, name) Values (278, 'F18.4 Liityntäpysäköintiviitta metro');
    Insert Into tmp_signs (othId, name) Values (279, 'F18.5 Liityntäpysäköintiviitta useita joukkoliikennevälineitä');
    Insert Into tmp_signs (othId, name) Values (164, 'F19 Jalankulun viitta');
    Insert Into tmp_signs (othId, name) Values (280, 'F20.1 Pyöräilyn viitta ilman etäisyyksiä');
    Insert Into tmp_signs (othId, name) Values (281, 'F20.2 Pyöräilyn viitta etäisyyslukemilla');
    Insert Into tmp_signs (othId, name) Values (282, 'F21.1 Pyöräilyn suunnistustaulu etäisyyslukemilla');
    Insert Into tmp_signs (othId, name) Values (283, 'F21.2 Pyöräilyn suunnistustaulu ilman etäisyyksiä');
    Insert Into tmp_signs (othId, name) Values (284, 'F22 Pyöräilyn etäisyystaulu');
    Insert Into tmp_signs (othId, name) Values (285, 'F23 Pyöräilyn paikannimi');
    Insert Into tmp_signs (othId, name) Values (113, 'F24.1 Umpitie edessä');
    Insert Into tmp_signs (othId, name) Values (114, 'F24.2 Umpitie oikealla/vasemmalla');
    Insert Into tmp_signs (othId, name) Values (286, 'F24.3 Umpitie');
    Insert Into tmp_signs (othId, name) Values (170, 'F25 Enimmäisnopeussuositus');
    Insert Into tmp_signs (othId, name) Values (171, 'F26 Etäisyystaulu');
    Insert Into tmp_signs (othId, name) Values (172, 'F27.1 Paikannimi');
    Insert Into tmp_signs (othId, name) Values (287, 'F27.1 Paikannimi');
    Insert Into tmp_signs (othId, name) Values (288, 'F27.1 Paikannimi');
    Insert Into tmp_signs (othId, name) Values (289, 'F27.2 Vesistön nimi');
    Insert Into tmp_signs (othId, name) Values (173, 'F28 Kansainvälisen pääliikenneväylän numero');
    Insert Into tmp_signs (othId, name) Values (175, 'F29 Valtatien numero');
    Insert Into tmp_signs (othId, name) Values (176, 'F30 Kantatien numero');
    Insert Into tmp_signs (othId, name) Values (400, 'F31 Seututien numero');
    Insert Into tmp_signs (othId, name) Values (177, 'F32 Muun maantien numero');
    Insert Into tmp_signs (othId, name) Values (290, 'F33 Kehätien numero');
    Insert Into tmp_signs (othId, name) Values (291, 'F34 Eritasoliittymän numero');
    Insert Into tmp_signs (othId, name) Values (174, 'F35 Opastus numeron tarkoittamalle tielle');
    Insert Into tmp_signs (othId, name) Values (292, 'F36 Varareitti');
    Insert Into tmp_signs (othId, name) Values (115, 'F37 Moottoritien tunnus');
    Insert Into tmp_signs (othId, name) Values (179, 'F38 Moottoriliikennetien tunnus');
    Insert Into tmp_signs (othId, name) Values (180, 'F39 Lentoasema');
    Insert Into tmp_signs (othId, name) Values (181, 'F40 Autolautta');
    Insert Into tmp_signs (othId, name) Values (293, 'F41 Matkustajasatama');
    Insert Into tmp_signs (othId, name) Values (182, 'F42 Tavarasatama');
    Insert Into tmp_signs (othId, name) Values (294, 'F43 Tavaraterminaali');
    Insert Into tmp_signs (othId, name) Values (183, 'F44 Teollisuusalue tai yritysalue');
    Insert Into tmp_signs (othId, name) Values (295, 'F45 Vähittäiskaupan suuryksikkö');
    Insert Into tmp_signs (othId, name) Values (116, 'F46.1 Pysäköinti');
    Insert Into tmp_signs (othId, name) Values (296, 'F46.2 Katettu pysäköinti');
    Insert Into tmp_signs (othId, name) Values (184, 'F47 Rautatieasema');
    Insert Into tmp_signs (othId, name) Values (185, 'F48 Linja-autoasema');
    Insert Into tmp_signs (othId, name) Values (297, 'F49 Keskusta');
    Insert Into tmp_signs (othId, name) Values (117, 'F50 Tietylle ajoneuvolle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (390, 'F50.1 Kuorma-autolle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (391, 'F50.2 Henkilöautolle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (392, 'F50.3 Linja-autolle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (393, 'F50.4 Pakettiautolle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (394, 'F50.5 Moottoripyörälle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (395, 'F50.6 Mopolle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (396, 'F50.7 Traktorille tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (397, 'F50.8 Matkailuajoneuvolle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (398, 'F50.9 Polkupyörälle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (186, 'F51 Vaarallisten aineiden kuljetukselle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (118, 'F52 Jalankulkijalle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (119, 'F53 Vammaiselle tarkoitettu reitti');
    Insert Into tmp_signs (othId, name) Values (187, 'F54.1 Reitti, jolla on portaat alas');
    Insert Into tmp_signs (othId, name) Values (298, 'F54.2 Reitti, jolla on portaat ylös');
    Insert Into tmp_signs (othId, name) Values (188, 'F55.1 Reitti ilman portaita alas');
    Insert Into tmp_signs (othId, name) Values (299, 'F55.2 Reitti ilman portaita ylös');
    Insert Into tmp_signs (othId, name) Values (300, 'F55.3 Pyörätuoliramppi alas');
    Insert Into tmp_signs (othId, name) Values (301, 'F55.4 Pyörätuoliramppi ylös');
    Insert Into tmp_signs (othId, name) Values (189, 'F56.1 Hätäuloskäynti vasemmalla');
    Insert Into tmp_signs (othId, name) Values (302, 'F56.2 Hätäuloskäynti oikealla');
    Insert Into tmp_signs (othId, name) Values (190, 'F57.1 Poistumisreitti (yksi)');
    Insert Into tmp_signs (othId, name) Values (303, 'F57.2 Poistumisreitti (useita)');
    Insert Into tmp_signs (othId, name) Values (304, 'G1 Palvelukohteen opastustaulu');
    Insert Into tmp_signs (othId, name) Values (305, 'G2 Palvelukohteen opastustaulu nuolella');
    Insert Into tmp_signs (othId, name) Values (306, 'G3 Palvelukohteen erkanemisviitta');
    Insert Into tmp_signs (othId, name) Values (120, 'G4 Palvelukohteen osoiteviitta');
    Insert Into tmp_signs (othId, name) Values (307, 'G5 Palvelukohteen osoiteviitan ennakkomerkki');
    Insert Into tmp_signs (othId, name) Values (308, 'G6 Radioaseman taajuus');
    Insert Into tmp_signs (othId, name) Values (309, 'G7 Opastuspiste');
    Insert Into tmp_signs (othId, name) Values (310, 'G8 Opastustoimisto');
    Insert Into tmp_signs (othId, name) Values (121, 'G9 Ensiapu');
    Insert Into tmp_signs (othId, name) Values (311, 'G10 Autokorjaamo');
    Insert Into tmp_signs (othId, name) Values (122, 'G11.1 Polttoaineen jakelu bensiini tai etanoli');
    Insert Into tmp_signs (othId, name) Values (312, 'G11.2 Polttoaineen jakelu paineistettu maakaasu');
    Insert Into tmp_signs (othId, name) Values (313, 'G11.3 Polttoaineen jakelu sähkö');
    Insert Into tmp_signs (othId, name) Values (314, 'G11.4 Polttoaineen jakelu vety');
    Insert Into tmp_signs (othId, name) Values (315, 'G12 Hotelli tai motelli');
    Insert Into tmp_signs (othId, name) Values (123, 'G13 Ruokailupaikka');
    Insert Into tmp_signs (othId, name) Values (316, 'G14 Kahvila tai pikaruokapaikka');
    Insert Into tmp_signs (othId, name) Values (124, 'G15 Käymälä');
    Insert Into tmp_signs (othId, name) Values (317, 'G16 Retkeilymaja');
    Insert Into tmp_signs (othId, name) Values (318, 'G17 Leirintäalue');
    Insert Into tmp_signs (othId, name) Values (319, 'G18 Matkailuajoneuvoalue');
    Insert Into tmp_signs (othId, name) Values (320, 'G19 Levähdysalue');
    Insert Into tmp_signs (othId, name) Values (321, 'G20 Ulkoilualue');
    Insert Into tmp_signs (othId, name) Values (322, 'G21 Hätäpuhelin');
    Insert Into tmp_signs (othId, name) Values (323, 'G22 Sammutin');
    Insert Into tmp_signs (othId, name) Values (324, 'G23 Museo tai historiallinen rakennus');
    Insert Into tmp_signs (othId, name) Values (325, 'G24 Maailmanperintökohde');
    Insert Into tmp_signs (othId, name) Values (326, 'G25 Luontokohde');
    Insert Into tmp_signs (othId, name) Values (327, 'G26 Näköalapaikka');
    Insert Into tmp_signs (othId, name) Values (328, 'G27 Eläintarha tai -puisto');
    Insert Into tmp_signs (othId, name) Values (329, 'G28 Muu nähtävyys');
    Insert Into tmp_signs (othId, name) Values (330, 'G29 Uintipaikka');
    Insert Into tmp_signs (othId, name) Values (331, 'G30 Kalastuspaikka');
    Insert Into tmp_signs (othId, name) Values (332, 'G31 Hiihtohissi');
    Insert Into tmp_signs (othId, name) Values (333, 'G32 Maastohiihtokeskus');
    Insert Into tmp_signs (othId, name) Values (334, 'G33 Golfkenttä');
    Insert Into tmp_signs (othId, name) Values (335, 'G34 Huvi- ja teemapuisto');
    Insert Into tmp_signs (othId, name) Values (336, 'G35 Mökkimajoitus');
    Insert Into tmp_signs (othId, name) Values (337, 'G36 Aamiaismajoitus');
    Insert Into tmp_signs (othId, name) Values (338, 'G37 Suoramyyntipaikka');
    Insert Into tmp_signs (othId, name) Values (339, 'G38 Käsityöpaja');
    Insert Into tmp_signs (othId, name) Values (340, 'G39 Kotieläinpiha');
    Insert Into tmp_signs (othId, name) Values (341, 'G40 Ratsastuspaikka');
    Insert Into tmp_signs (othId, name) Values (342, 'G41.1 Matkailutie (pelkkä teksti)');
    Insert Into tmp_signs (othId, name) Values (343, 'G41.2 Matkailutie (kuva ja teksti)');
    Insert Into tmp_signs (othId, name) Values (344, 'G42 Tilapäinen opastusmerkki');
    Insert Into tmp_signs (othId, name) Values (345, 'H1 Kohde risteävässä suunnassa');
    Insert Into tmp_signs (othId, name) Values (346, 'H2.1 Kohde nuolen suunnassa');
    Insert Into tmp_signs (othId, name) Values (347, 'H2.2 Kohde nuolen suunnassa ja etäisyys');
    Insert Into tmp_signs (othId, name) Values (348, 'H2.3 Kohde edessä ja etäisyys');
    Insert Into tmp_signs (othId, name) Values (148, 'H3 Vaikutusalueen pituus');
    Insert Into tmp_signs (othId, name) Values (149, 'H4 Etäisyys kohteeseen');
    Insert Into tmp_signs (othId, name) Values (138, 'H5 Etäisyys pakolliseen pysäyttämiseen');
    Insert Into tmp_signs (othId, name) Values (45, 'H6 Vapaa leveys');
    Insert Into tmp_signs (othId, name) Values (46, 'H7 Vapaa korkeus');
    Insert Into tmp_signs (othId, name) Values (139, 'H8 Sähköjohdon korkeus');
    Insert Into tmp_signs (othId, name) Values (140, 'H9.1 Vaikutusalue molempiin suuntiin oikealle ja vasemmalle');
    Insert Into tmp_signs (othId, name) Values (141, 'H9.2 Vaikutusalue molempiin suuntiin eteen- ja taaksepäin');
    Insert Into tmp_signs (othId, name) Values (142, 'H10 Vaikutusalue nuolen suuntaan');
    Insert Into tmp_signs (othId, name) Values (143, 'H10 Vaikutusalue nuolen suuntaan');
    Insert Into tmp_signs (othId, name) Values (144, 'H11 Vaikutusalue päättyy');
    Insert Into tmp_signs (othId, name) Values (52, 'H12.1 Henkilöauto');
    Insert Into tmp_signs (othId, name) Values (53, 'H12.2 Linja-auto');
    Insert Into tmp_signs (othId, name) Values (54, 'H12.3 Kuorma-auto');
    Insert Into tmp_signs (othId, name) Values (55, 'H12.4 Pakettiauto');
    Insert Into tmp_signs (othId, name) Values (150, 'H12.5 Matkailuperävaunu');
    Insert Into tmp_signs (othId, name) Values (349, 'H12.6 Matkailuauto');
    Insert Into tmp_signs (othId, name) Values (56, 'H12.7 Invalidin ajoneuvo');
    Insert Into tmp_signs (othId, name) Values (57, 'H12.8 Moottoripyörä');
    Insert Into tmp_signs (othId, name) Values (151, 'H12.9 Mopo');
    Insert Into tmp_signs (othId, name) Values (58, 'H12.10 Polkupyörä');
    Insert Into tmp_signs (othId, name) Values (350, 'H12.11 Moottorikelkka');
    Insert Into tmp_signs (othId, name) Values (351, 'H12.12 Traktori');
    Insert Into tmp_signs (othId, name) Values (352, 'H12.13 Vähäpäästöinen ajoneuvo');
    Insert Into tmp_signs (othId, name) Values (353, 'H13.1 Pysäköintitapa reunakiven päälle');
    Insert Into tmp_signs (othId, name) Values (354, 'H13.2 Pysäköintitapa reunakiven laitaan');
    Insert Into tmp_signs (othId, name) Values (47, 'H14 Kielto ryhmän A vaarallisten aineiden kuljetukselle');
    Insert Into tmp_signs (othId, name) Values (48, 'H15 Kielto ryhmän B vaarallisten aineiden kuljetukselle');
    Insert Into tmp_signs (othId, name) Values (355, 'H16 Tunneliluokka');
    Insert Into tmp_signs (othId, name) Values (49, 'H17.1 Voimassaoloaika arkisin ma-pe');
    Insert Into tmp_signs (othId, name) Values (50, 'H17.2 Voimassaoloaika arkilauantaisin');
    Insert Into tmp_signs (othId, name) Values (145, 'H17.3 Voimassaoloaika sunnuntaisin ja pyhinä');
    Insert Into tmp_signs (othId, name) Values (51, 'H18 Aikarajoitus');
    Insert Into tmp_signs (othId, name) Values (60, 'H19.1 Pysäköintiajan alkamisen osoittamisvelvollisuus (keltainen pohja)');
    Insert Into tmp_signs (othId, name) Values (356, 'H19.2 Pysäköintiajan alkamisen osoittamisvelvollisuus (sininen pohja)');
    Insert Into tmp_signs (othId, name) Values (59, 'H20 Maksullinen pysäköinti');
    Insert Into tmp_signs (othId, name) Values (357, 'H20 Maksullinen pysäköinti');
    Insert Into tmp_signs (othId, name) Values (358, 'H21 Latauspaikka');
    Insert Into tmp_signs (othId, name) Values (146, 'H22.1 Etuajooikeutetun liikenteen suunta');
    Insert Into tmp_signs (othId, name) Values (359, 'H22.1 Etuajooikeutetun liikenteen suunta');
    Insert Into tmp_signs (othId, name) Values (360, 'H22.2 Etuajooikeutetun liikenteen suunta kääntyville');
    Insert Into tmp_signs (othId, name) Values (361, 'H23.1 Kaksisuuntainen pyörätie (keltainen pohja)');
    Insert Into tmp_signs (othId, name) Values (362, 'H23.2 Kaksisuuntainen pyörätie (sininen pohja)');
    Insert Into tmp_signs (othId, name) Values (61, 'H24 Tekstillinen lisäkilpi');
    Insert Into tmp_signs (othId, name) Values (62, 'H25 Huoltoajo sallittu');
    Insert Into tmp_signs (othId, name) Values (363, 'H26 Hätäpuhelin ja sammutin');
    Insert Into tmp_signs (othId, name) Values (364, 'I1 Sulkupuomi');
    Insert Into tmp_signs (othId, name) Values (365, 'I2.1 Sulkuaita');
    Insert Into tmp_signs (othId, name) Values (366, 'I2.2 Sulkuaita nuolilla');
    Insert Into tmp_signs (othId, name) Values (367, 'I3.1 Sulkupylväs vasemmalla');
    Insert Into tmp_signs (othId, name) Values (368, 'I3.2 Sulkupylväs oikealla');
    Insert Into tmp_signs (othId, name) Values (369, 'I3.3 Sulkupylväs');
    Insert Into tmp_signs (othId, name) Values (370, 'I4 Sulkukartio');
    Insert Into tmp_signs (othId, name) Values (371, 'I5 Taustamerkki');
    Insert Into tmp_signs (othId, name) Values (372, 'I6 Kaarteen suuntamerkki');
    Insert Into tmp_signs (othId, name) Values (373, 'I7.1 Reunamerkki vasemmalla');
    Insert Into tmp_signs (othId, name) Values (374, 'I7.2 Reunamerkki oikealla');
    Insert Into tmp_signs (othId, name) Values (375, 'I8 Korkeusmerkki');
    Insert Into tmp_signs (othId, name) Values (376, 'I9 Alikulun korkeusmitta');
    Insert Into tmp_signs (othId, name) Values (377, 'I10.1 Liikennemerkkipylvään tehostamismerkki (sinivalkoinen)');
    Insert Into tmp_signs (othId, name) Values (378, 'I10.2 Liikennemerkkipylvään tehostamismerkki (keltamusta)');
    Insert Into tmp_signs (othId, name) Values (379, 'I11 Erkanemismerkki');
    Insert Into tmp_signs (othId, name) Values (380, 'I12.1 Reunapaalu vasemmalla');
    Insert Into tmp_signs (othId, name) Values (381, 'I12.2 Reunapaalu oikealla');
    Insert Into tmp_signs (othId, name) Values (382, 'I13 Siirtokehotus');
    Insert Into tmp_signs (othId, name) Values (383, 'I14 Paikannusmerkki');
    Insert Into tmp_signs (othId, name) Values (384, 'I15 Automaattinen liikennevalvonta');
    Insert Into tmp_signs (othId, name) Values (385, 'I16 Tekninen valvonta');
    Insert Into tmp_signs (othId, name) Values (386, 'I17.1 Poronhoitoalue tekstillinen');
    Insert Into tmp_signs (othId, name) Values (387, 'I17.2 Poronhoitoalue ilman tekstiä');
    Insert Into tmp_signs (othId, name) Values (388, 'I18 Yleinen nopeusrajoitus rajalla');
    Insert Into tmp_signs (othId, name) Values (389, 'I19 Valtion raja');

    COMMIT;

    -- Save the property Id for PUBLIC_ID ='trafficSigns_type' of the traffic signs (asset_type_id = 300)
	SELECT ID INTO v_property_id
	FROM PROPERTY
	WHERE ASSET_TYPE_ID  = 300
	AND PUBLIC_ID ='trafficSigns_type';

    -- Update the name of the current traffic signs
	MERGE INTO ENUMERATED_VALUE ev
    	USING (SELECT * FROM TMP_SIGNS) ts
    	ON (ev.PROPERTY_ID  = v_property_id AND ts.othId = ev.value)
  	WHEN MATCHED THEN
    	UPDATE SET ev.NAME_FI = ts.name, ev.MODIFIED_DATE = SYSDATE, ev.MODIFIED_BY = 'db_migration_v231'
	    WHERE ev.NAME_FI <> ts.name;
	WHEN NOT MATCHED  THEN
        INSERT INTO ENUMERATED_VALUE (id, PROPERTY_ID, VALUE, NAME_FI, CREATED_BY, CREATED_DATE )
	    VALUES (primary_key_seq.nextval, v_property_id, ts.othId, ts.name, 'db_migration_v231', SYSDATE );

    COMMIT;

    -- We no longer need the temporary table
   execute immediate 'TRUNCATE TABLE tmp_signs';
   execute immediate 'DROP TABLE tmp_signs';

END;
