CREATE INDEX UNKNOWN_SPEED_LIMIT_MC_AC ON UNKNOWN_SPEED_LIMIT(MUNICIPALITY_CODE, ADMINISTRATIVE_CLASS);
CREATE INDEX LRM_POSITION_MML_IDX ON LRM_POSITION(MML_ID);
CREATE INDEX MANOEUVRE_EXCEPTIONS_MID ON MANOEUVRE_EXCEPTIONS(MANOEUVRE_ID);
ALTER TABLE MANOEUVRE_EXCEPTIONS
ADD CONSTRAINT MANOEUVRE_FK
FOREIGN KEY (MANOEUVRE_ID)
REFERENCES MANOEUVRE (ID);