CREATE INDEX ELEMENT_MANOEUVRE_IDX ON MANOEUVRE_ELEMENT (MANOEUVRE_ID);
CREATE INDEX ELEMENT_SOURCE_LINK_IDX ON MANOEUVRE_ELEMENT (LINK_ID, ELEMENT_TYPE);
CREATE INDEX M_VALID_PERIOD_MID ON MANOEUVRE_VALIDITY_PERIOD (MANOEUVRE_ID);
CREATE INDEX MANOEUVRE_VALID_TO_IDX ON MANOEUVRE (VALID_TO);
