CREATE TABLE "MISSING_ROAD_ADDRESS"
   (	"LINK_ID" NUMBER(38,0) 			NOT NULL,
		"START_ADDR_M" NUMBER			NOT NULL,
		"END_ADDR_M" NUMBER				NOT NULL,
		"ANOMALY_CODE" CHAR(1 BYTE)		NOT NULL,
		PRIMARY KEY ("LINK_ID","START_ADDR_M","END_ADDR_M")
   );
