CREATE TABLE "MISSING_ROAD_ADDRESS"
   (	"LINK_ID" NUMBER(38,0) 			NOT NULL,
		"START_ADDR_M" NUMBER			NOT NULL,
		"END_ADDR_M" NUMBER				NOT NULL,
		"ANOMALY_CODE" CHAR(1 BYTE)		NOT NULL
   );


CREATE INDEX GAP_ROAD_ADDRESS_ID ON MISSING_ROAD_ADDRESS (START_ADDR_M, END_ADDR_M);