package fi.liikennevirasto.digiroad2.service.pointasset

import fi.liikennevirasto.digiroad2._
import fi.liikennevirasto.digiroad2.asset.{AutoGeneratedUsername, BoundingRectangle, LinkGeomSource, PropertyValue, SimplePointAssetProperty}
import fi.liikennevirasto.digiroad2.client.RoadLinkInfo
import fi.liikennevirasto.digiroad2.dao.pointasset.{PostGISRailwayCrossingDao, RailwayCrossing}
import fi.liikennevirasto.digiroad2.linearasset.{LinkId, RoadLink, RoadLinkLike}
import fi.liikennevirasto.digiroad2.service.RoadLinkService
import fi.liikennevirasto.digiroad2.user.User
import org.joda.time.DateTime

case class IncomingRailwayCrossing(lon: Double, lat: Double, linkId: String, propertyData: Set[SimplePointAssetProperty], mValue: Option[Double] = None) extends IncomingPointAsset
case class IncomingRailwayCrossingtAsset(linkId: String, mValue: Long, propertyData: Set[SimplePointAssetProperty])  extends IncomePointAsset

class RailwayCrossingService(val roadLinkService: RoadLinkService) extends PointAssetOperations {
  type IncomingAsset = IncomingRailwayCrossing
  type PersistedAsset = RailwayCrossing

  override def typeId: Int = 230

  val namePublicId = "rautatien_tasoristeyksen_nimi"
  val safetyEquipmentPublicId = "turvavarustus"
  val codePublicId = "tasoristeystunnus"

  override def setAssetPosition(asset: IncomingRailwayCrossing, geometry: Seq[Point], mValue: Double): IncomingRailwayCrossing = {
    GeometryUtils.calculatePointFromLinearReference(geometry, mValue) match {
      case Some(point) =>
        asset.copy(lon = point.x, lat = point.y)
      case _ =>
        asset
    }
  }

  override def fetchPointAssets(queryFilter: String => String, roadLinks: Seq[RoadLinkLike]): Seq[RailwayCrossing] = PostGISRailwayCrossingDao.fetchByFilter(queryFilter)

  override def setFloating(persistedAsset: RailwayCrossing, floating: Boolean) = {
    persistedAsset.copy(floating = floating)
  }

  override def getByBoundingBox(user: User, bounds: BoundingRectangle) : Seq[PersistedAsset] = {
    val (roadLinks, _) = roadLinkService.getRoadLinksWithComplementaryAndChanges(bounds,asyncMode = false)
    super.getByBoundingBox(user, bounds, roadLinks)
  }

  override def createOperation(asset: PersistedAsset, adjustment: AssetUpdate): PersistedAsset = {
    new PersistedAsset(adjustment.assetId, adjustment.linkId, adjustment.lon, adjustment.lat, adjustment.mValue,
      adjustment.floating, asset.timeStamp, asset.municipalityCode, asset.propertyData, asset.createdBy, asset.createdAt,
      asset.modifiedBy, asset.modifiedAt, asset.linkSource, asset.externalId)
  }

  override def adjustmentOperation(persistedAsset: PersistedAsset, adjustment: AssetUpdate, roadLink: RoadLinkInfo): Long = {
    val updated = IncomingRailwayCrossing(adjustment.lon, adjustment.lat, adjustment.linkId, persistedAsset.propertyData.map(prop => SimplePointAssetProperty(prop.publicId, prop.values)).toSet)
    updateWithoutTransaction(adjustment.assetId, updated, roadLink.geometry, roadLink.municipality.getOrElse(throw new NoSuchElementException(s"${roadLink.linkId} does not have municipality code")), persistedAsset.linkSource,
      persistedAsset.createdBy.getOrElse(AutoGeneratedUsername.generatedInUpdate), Some(adjustment.mValue), Some(adjustment.timeStamp), true)
  }

  def createFromCoordinates(incomingRailwayCrossing: IncomingRailwayCrossing, roadLink: RoadLink, username: String, isFloating: Boolean): Long = {
    if(isFloating)
      createFloatingWithoutTransaction(incomingRailwayCrossing.copy(linkId = LinkId.Unknown.value), username, roadLink)
    else {
      checkDuplicates(incomingRailwayCrossing) match {
        case Some(existingAsset) =>
          updateWithoutTransaction(existingAsset.id, incomingRailwayCrossing, roadLink, username, Some(existingAsset.mValue), Some(existingAsset.timeStamp))
        case _ =>
          create(incomingRailwayCrossing, username, roadLink, false)
      }
    }
  }

  def getProperty(incomingRailwayCrossing: IncomingRailwayCrossing, property: String) : Option[PropertyValue] = {
    incomingRailwayCrossing.propertyData.find(p => p.publicId == property).get.values.map(_.asInstanceOf[PropertyValue]).headOption
  }

  def checkDuplicates(incomingRailwayCrossing: IncomingRailwayCrossing): Option[RailwayCrossing] = {
    val position = Point(incomingRailwayCrossing.lon, incomingRailwayCrossing.lat)
    val safetyEquipmentType = getProperty(incomingRailwayCrossing, safetyEquipmentPublicId).get.propertyValue.toString
    val signsInRadius = PostGISRailwayCrossingDao.fetchByFilter(withBoundingBoxFilter(position, TwoMeters)).filter(
      asset =>
        GeometryUtils.geometryLength(Seq(position, Point(asset.lon, asset.lat))) <= TwoMeters &&
          safetyEquipmentType == getProperty(asset.propertyData, safetyEquipmentPublicId).get.propertyValue.toString
    )
    if(signsInRadius.nonEmpty) Some(getLatestModifiedAsset(signsInRadius)) else None
  }

  def getLatestModifiedAsset(signs: Seq[RailwayCrossing]): RailwayCrossing = {
    signs.maxBy(sign => sign.modifiedAt.getOrElse(sign.createdAt.get).getMillis)
  }

  def createFloatingWithoutTransaction(asset: IncomingRailwayCrossing, username: String, roadLink: RoadLink): Long = {
    val mValue = GeometryUtils.calculateLinearReferenceFromPoint(Point(asset.lon, asset.lat), roadLink.geometry)
    PostGISRailwayCrossingDao.create(setAssetPosition(asset, roadLink.geometry, mValue), mValue, roadLink.municipalityCode, username, createTimeStamp(), roadLink.linkSource)
  }

  override def create(asset: IncomingRailwayCrossing, username: String, roadLink: RoadLink, newTransaction: Boolean): Long = {
    val mValue = GeometryUtils.calculateLinearReferenceFromPoint(Point(asset.lon, asset.lat), roadLink.geometry)
    if(newTransaction) {
      withDynTransaction {
        PostGISRailwayCrossingDao.create(setAssetPosition(asset, roadLink.geometry, mValue), mValue, roadLink.municipalityCode, username, createTimeStamp(), roadLink.linkSource)
      }
    } else {
      PostGISRailwayCrossingDao.create(setAssetPosition(asset, roadLink.geometry, mValue), mValue, roadLink.municipalityCode, username, createTimeStamp(), roadLink.linkSource)
    }
  }

  override def update(id: Long, updatedAsset: IncomingRailwayCrossing, roadLink: RoadLink, username: String): Long = {
    withDynTransaction {
      updateWithoutTransaction(id, updatedAsset, roadLink, username, updatedAsset.mValue, None)
    }
  }

  def updateWithoutTransaction(id: Long, updatedAsset: IncomingRailwayCrossing,roadLink: RoadLink, username: String, mValue : Option[Double], timeStamp: Option[Long]): Long = {
    updateWithoutTransaction(id, updatedAsset, roadLink.geometry, roadLink.municipalityCode, roadLink.linkSource,
      username, mValue, timeStamp)
  }

  def updateWithoutTransaction(id: Long, updatedAsset: IncomingRailwayCrossing, linkGeom: Seq[Point], linkMunicipality: Int,
                               linkSource: LinkGeomSource, username: String, mValue : Option[Double], timeStamp: Option[Long], fromPointAssetUpdater: Boolean = false): Long = {
    val value = mValue.getOrElse(GeometryUtils.calculateLinearReferenceFromPoint(Point(updatedAsset.lon, updatedAsset.lat), linkGeom))
    getPersistedAssetsByIdsWithoutTransaction(Set(id)).headOption.getOrElse(throw new NoSuchElementException("Asset not found")) match {
      case old if (old.lat != updatedAsset.lat || old.lon != updatedAsset.lon) && !fromPointAssetUpdater =>
        expireWithoutTransaction(id)
        PostGISRailwayCrossingDao.create(setAssetPosition(updatedAsset, linkGeom, value), value, linkMunicipality, username,
          timeStamp.getOrElse(createTimeStamp()), linkSource, old.createdBy, old.createdAt, old.externalId, fromPointAssetUpdater, old.modifiedBy, old.modifiedAt)
      case _ =>
        PostGISRailwayCrossingDao.update(id, updatedAsset, value, linkMunicipality, username,
          Some(timeStamp.getOrElse(createTimeStamp())), linkSource, fromPointAssetUpdater)
    }
  }

  override def toIncomingAsset(asset: IncomePointAsset, link: RoadLink) : Option[IncomingRailwayCrossing] = {
    GeometryUtils.calculatePointFromLinearReference(link.geometry, asset.mValue).map {
      point =>  IncomingRailwayCrossing(point.x, point.y, link.linkId, asset.asInstanceOf[IncomingRailwayCrossingtAsset].propertyData)
    }
  }

  def getCodeMaxSize : Long  =   withDynTransaction { PostGISRailwayCrossingDao.getCodeMaxSize }

  override def getChanged(sinceDate: DateTime, untilDate: DateTime, token: Option[String] = None): Seq[ChangedPointAsset] = { throw new UnsupportedOperationException("Not Supported Method") }

  override def fetchPointAssetsWithExpired(queryFilter: String => String, roadLinks: Seq[RoadLinkLike]): Seq[RailwayCrossing] =  { throw new UnsupportedOperationException("Not Supported Method") }

  override def fetchPointAssetsWithExpiredLimited(queryFilter: String => String, token: Option[String]): Seq[RailwayCrossing] = { throw new UnsupportedOperationException("Not Supported Method") }
}


