
ALTER TABLE manoeuvre_validity_period
    ADD (
          START_MINUTE INTEGER DEFAULT 0 NOT NULL,
          END_MINUTE INTEGER DEFAULT 0 NOT NULL
        );


ALTER TABLE PROHIBITION_VALIDITY_PERIOD
    ADD (
          START_MINUTE INTEGER DEFAULT 0 NOT NULL,
          END_MINUTE INTEGER DEFAULT 0 NOT NULL
        );